import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals
import Mathlib.MeasureTheory.Integral.IntegralEqImproper

/-!
# The bounded-generator Laplace resolvent identity

For a bounded generator whose exponential is contractive at nonnegative
times, the Bochner integral of the exponentially damped orbit is the
bounded inverse of `lambda I - G`.  Taking an inner product gives the
Green--Kubo resolvent identity used in (9)--(10).

Paper: `manuscript.tex:577-608`.
-/

noncomputable section

open ComplexConjugate InnerProductSpace MeasureTheory NormedSpace RCLike
open scoped ComplexConjugate InnerProduct

namespace Manhattan.Operator

variable {E : Type*} [NormedAddCommGroup E]
  [InnerProductSpace ℂ E] [CompleteSpace E]

/-- The complex space read as a real normed space. -/
local instance : NormedSpace ℝ E := NormedSpace.restrictScalars ℝ ℂ E

/-- The uniformly continuous semigroup generated by a bounded operator. -/
def operatorSemigroup (G : E →L[ℂ] E) (t : ℝ) : E →L[ℂ] E :=
  exp ℝ (t • G)

/-- The operator `lambda I - G`. -/
def resolventOperator (G : E →L[ℂ] E) (lambda : ℝ) : E →L[ℂ] E :=
  lambda • ContinuousLinearMap.id ℂ E - G

/-- An exponentially damped semigroup orbit. -/
def dampedOrbit (G : E →L[ℂ] E) (lambda : ℝ) (u : E) (t : ℝ) : E :=
  Real.exp (-lambda * t) • operatorSemigroup G t u

/-- The vector-valued Laplace transform of a semigroup orbit. -/
def laplaceVector (G : E →L[ℂ] E) (lambda : ℝ) (u : E) : E :=
  ∫ t in Set.Ioi 0, dampedOrbit G lambda u t

theorem operatorSemigroup_hasDerivAt (G : E →L[ℂ] E) (u : E) (t : ℝ) :
    HasDerivAt (fun s : ℝ ↦ operatorSemigroup G s u)
      (G (operatorSemigroup G t u)) t := by
  let ev : (E →L[ℂ] E) →L[ℝ] E :=
    (ContinuousLinearMap.apply ℂ E u).restrictScalars ℝ
  have hexp := hasFDerivAt_exp_smul_const' (𝕂 := ℝ) G t
  have h := ev.hasFDerivAt.comp t hexp
  simpa [ev, operatorSemigroup, ContinuousLinearMap.mul_apply] using h

omit [CompleteSpace E] in
theorem generator_commutes_operatorSemigroup (G : E →L[ℂ] E) (t : ℝ) :
    Commute G (operatorSemigroup G t) := by
  apply Commute.exp_right ℝ
  exact (Commute.refl G).smul_right t

theorem dampedOrbit_hasDerivAt (G : E →L[ℂ] E) (lambda t : ℝ) (u : E) :
    HasDerivAt (dampedOrbit G lambda u)
      (-resolventOperator G lambda (dampedOrbit G lambda u t)) t := by
  have hs : HasDerivAt (fun s : ℝ ↦ Real.exp (-lambda * s))
      (-lambda * Real.exp (-lambda * t)) t := by
    convert (Real.hasDerivAt_exp (-lambda * t)).comp t
      ((hasDerivAt_id t).const_mul (-lambda)) using 1
    all_goals ring
  have ho := operatorSemigroup_hasDerivAt G u t
  convert hs.smul ho using 1
  simp only [resolventOperator, dampedOrbit, ContinuousLinearMap.sub_apply,
    ContinuousLinearMap.smul_apply, ContinuousLinearMap.id_apply,
    ContinuousLinearMap.map_smul_of_tower, neg_sub, smul_smul]
  module

omit [CompleteSpace E] in
theorem dampedOrbit_norm_le (G : E →L[ℂ] E) (lambda : ℝ) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1)
    {t : ℝ} (ht : 0 ≤ t) :
    ‖dampedOrbit G lambda u t‖ ≤ Real.exp (-lambda * t) * ‖u‖ := by
  rw [dampedOrbit, norm_smul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  gcongr
  exact (ContinuousLinearMap.le_opNorm _ _).trans
    (mul_le_of_le_one_left (norm_nonneg u) (hcontract t ht))

theorem integrableOn_dampedOrbit (G : E →L[ℂ] E) {lambda : ℝ} (hlambda : 0 < lambda)
    (u : E) (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    IntegrableOn (dampedOrbit G lambda u) (Set.Ioi 0) := by
  apply Integrable.mono'
    ((integrableOn_exp_mul_Ioi (a := -lambda) (by linarith) 0).mul_const ‖u‖)
  · exact (continuous_iff_continuousAt.2 fun t ↦
      (dampedOrbit_hasDerivAt G lambda t u).continuousAt).aestronglyMeasurable
  · filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    simpa only [neg_mul] using dampedOrbit_norm_le G lambda u hcontract ht.le

omit [CompleteSpace E] in
theorem tendsto_dampedOrbit_atTop (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Filter.Tendsto (dampedOrbit G lambda u) Filter.atTop (nhds 0) := by
  rw [Metric.tendsto_atTop]
  intro epsilon hepsilon
  have hexp : Filter.Tendsto (fun t : ℝ ↦ Real.exp (-lambda * t) * ‖u‖)
      Filter.atTop (nhds 0) := by
    have h := (Real.tendsto_exp_neg_atTop_nhds_zero.comp
      (Filter.tendsto_id.const_mul_atTop hlambda)).mul_const ‖u‖
    simpa only [Function.comp_apply, id_eq, zero_mul, neg_mul] using h
  rw [Metric.tendsto_atTop] at hexp
  obtain ⟨a, ha⟩ := hexp epsilon hepsilon
  refine ⟨max a 0, fun b hb ↦ ?_⟩
  rw [dist_zero_right]
  exact (dampedOrbit_norm_le G lambda u hcontract (le_trans (le_max_right _ _) hb)).trans_lt
    (by simpa [dist_zero_right] using ha b (le_trans (le_max_left _ _) hb))

theorem integrableOn_resolvent_dampedOrbit (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    IntegrableOn (fun t ↦ resolventOperator G lambda (dampedOrbit G lambda u t))
      (Set.Ioi 0) :=
  (resolventOperator G lambda).integrable_comp
    (integrableOn_dampedOrbit G hlambda u hcontract)

/-- The Laplace vector is a right inverse for `lambda I - G`. -/
theorem resolventOperator_laplaceVector (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    resolventOperator G lambda (laplaceVector G lambda u) = u := by
  have hFTC := integral_Ioi_of_hasDerivAt_of_tendsto'
    (a := (0 : ℝ)) (m := (0 : E))
    (fun t _ ↦ dampedOrbit_hasDerivAt G lambda t u)
    ((integrableOn_resolvent_dampedOrbit G hlambda u hcontract).neg)
    (tendsto_dampedOrbit_atTop G hlambda u hcontract)
  rw [integral_neg] at hFTC
  rw [laplaceVector, ← ContinuousLinearMap.integral_comp_comm]
  · apply neg_injective
    simpa [dampedOrbit, operatorSemigroup] using hFTC
  exact integrableOn_dampedOrbit G hlambda u hcontract

/-- The Laplace vector is also a left inverse for `lambda I - G`. -/
theorem laplaceVector_resolventOperator (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    laplaceVector G lambda (resolventOperator G lambda u) = u := by
  rw [laplaceVector]
  calc
    ∫ t in Set.Ioi 0, dampedOrbit G lambda (resolventOperator G lambda u) t =
        ∫ t in Set.Ioi 0,
          resolventOperator G lambda (dampedOrbit G lambda u t) := by
            apply integral_congr_ae
            filter_upwards with t
            have hcomm : G (operatorSemigroup G t u) =
                operatorSemigroup G t (G u) := by
              simpa [ContinuousLinearMap.mul_apply] using
                congrArg (fun T : E →L[ℂ] E ↦ T u)
                  (generator_commutes_operatorSemigroup G t).eq
            have hpoint : operatorSemigroup G t (resolventOperator G lambda u) =
                resolventOperator G lambda (operatorSemigroup G t u) := by
              simp only [resolventOperator, ContinuousLinearMap.sub_apply,
                ContinuousLinearMap.smul_apply, ContinuousLinearMap.id_apply, map_sub,
                ContinuousLinearMap.map_smul_of_tower]
              rw [hcomm]
            rw [dampedOrbit, dampedOrbit,
              ContinuousLinearMap.map_smul_of_tower, hpoint]
    _ = resolventOperator G lambda (laplaceVector G lambda u) := by
      rw [laplaceVector, ContinuousLinearMap.integral_comp_comm]
      exact integrableOn_dampedOrbit G hlambda u hcontract
    _ = u := resolventOperator_laplaceVector G hlambda u hcontract

theorem resolventOperator_injective (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Function.Injective (resolventOperator G lambda) := by
  intro u v huv
  rw [← laplaceVector_resolventOperator G hlambda u hcontract,
    ← laplaceVector_resolventOperator G hlambda v hcontract, huv]

theorem resolventOperator_bijective (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Function.Bijective (resolventOperator G lambda) :=
  ⟨resolventOperator_injective G hlambda hcontract,
    fun u ↦ ⟨laplaceVector G lambda u,
      resolventOperator_laplaceVector G hlambda u hcontract⟩⟩

/-- The bounded equivalence `lambda I - G`, with inverse supplied by the
Laplace transform. -/
def resolventEquiv (G : E →L[ℂ] E) {lambda : ℝ} (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) : E ≃L[ℂ] E :=
  ContinuousLinearEquiv.ofBijective (resolventOperator G lambda)
    (LinearMap.ker_eq_bot.mpr (resolventOperator_bijective G hlambda hcontract).1)
    (LinearMap.range_eq_top.mpr (resolventOperator_bijective G hlambda hcontract).2)

theorem resolventEquiv_symm_apply (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    (resolventEquiv G hlambda hcontract).symm u = laplaceVector G lambda u := by
  apply (resolventEquiv G hlambda hcontract).injective
  simpa [resolventEquiv] using
    (resolventOperator_laplaceVector G hlambda u hcontract).symm

/-- The scalar integrand in the Green--Kubo identity. -/
def semigroupCorrelation (G : E →L[ℂ] E)
    (lambda : ℝ) (u : E) (t : ℝ) : ℂ :=
  (Real.exp (-lambda * t) : ℂ) * ⟪u, operatorSemigroup G t u⟫_ℂ

/-- Bochner-integral form of the Green--Kubo resolvent identity. -/
theorem integral_inner_operatorSemigroup_eq_resolvent (G : E →L[ℂ] E)
    {lambda : ℝ} (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    (∫ t in Set.Ioi 0, semigroupCorrelation G lambda u t) =
      ⟪u, (resolventEquiv G hlambda hcontract).symm u⟫_ℂ := by
  rw [resolventEquiv_symm_apply G hlambda u hcontract, laplaceVector]
  change (∫ t in Set.Ioi 0, semigroupCorrelation G lambda u t) =
    (innerSL ℂ u) (∫ t in Set.Ioi 0, dampedOrbit G lambda u t)
  calc
    _ = ∫ t in Set.Ioi 0, (innerSL ℂ u) (dampedOrbit G lambda u t) := by
      apply integral_congr_ae
      filter_upwards with t
      simp [semigroupCorrelation, dampedOrbit]
    _ = _ := ContinuousLinearMap.integral_comp_comm (L := innerSL ℂ u)
      (integrableOn_dampedOrbit G hlambda u hcontract)

end Manhattan.Operator
